version: "3.9"

services:
  backend:
    build: ./backend
    container_name: industrial-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://industrial:industrial@db:5432/industrial_db

  db:
    image: postgres:15
    container_name: industrial-db
    environment:
      POSTGRES_USER: industrial
      POSTGRES_PASSWORD: industrial
      POSTGRES_DB: industrial_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: